import "./globals.css";
import { Inter } from "next/font/google";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import AllMoviesProvider from "@/providers/data/AllMoviesData";
import ReactQueryProviders from "@/providers/ReactQuerySetup/ReactQueryProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProviders>
          <AllMoviesProvider>{children}</AllMoviesProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
