"use client";
// 
import "./globals.css";
import { Inter } from "next/font/google";
import MainNav from "@/components/pages/HomePage/MainNav";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import AllMoviesProvider from "@/providers/data/AllMoviesData";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AllMoviesProvider>
      <html lang="en">
        <body className={inter.className}>
          <MainNav />
          {children}
          <a className="bg-red-500 my-4 block mx-auto text-center p-4 rounded-md">
            Download
          </a>
        </body>
      </html>
    </AllMoviesProvider>
  );
}
